name: wallpaper_app
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

version: 1.0.0+1
environment:
  sdk: ">=2.2.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  font_awesome_flutter: ^8.8.1
  firebase_auth: ^0.15.3
  cloud_firestore: ^0.12.9+6
  firebase_storage: ^3.1.1
  google_sign_in: ^4.1.1
  flutter_staggered_grid_view: ^0.3.2
  cached_network_image: ^2.3.3
  image_picker: ^0.6.2+3
  firebase_ml_vision: ^0.9.3+5

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/


  fonts:
    - family: productsans
      fonts:
        - asset: assets/ProductSans-Regular.ttf
